LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\travel_class.txt' REPLACE INTO TABLE TRAVEL_CLASS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,CLASS,DESCRIPTION);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\pass_type.txt' REPLACE INTO TABLE PASS_TYPE FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,TYPE,DESCRIPTION);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\airlines.txt' REPLACE INTO TABLE AIRLINES FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,NAME,ALIAS,IATA,ICAO,CALLSIGN,COUNTRY, ACTIVE);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\airports.txt' REPLACE INTO TABLE AIRPORTS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,NAME,CITY,COUNTRY,IATA,LATITUDE,LONGITUDE, ALTITUDE,TIMEZONE,DST,TZ);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\route.txt' REPLACE INTO TABLE ROUTE FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,AIRLINE,AIRLINE_ID,SOURCE_AIRPORT,SOURCE_AIRPORT_ID,DEST_AIRPORT,DEST_AIRPORT_ID);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\data\\airplanes.csv' REPLACE INTO TABLE airplanes FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (AIRPLANE_ID, ROUTE_ID);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\data\\airplanes_info.csv' REPLACE INTO TABLE airplanes_info FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (PLANE_ID,CLASS_ID,NUM_SEATS,NUM_FARE);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\data\\airplanes_weekly_schedule.csv' REPLACE INTO TABLE airplanes_weekly_schedule FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (FLIGHT_ID, WEEK_DAYS, J_TIME, S_TIME);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\data\\schedule.csv' REPLACE INTO TABLE schedule FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (AIRPLANE_ID, STARTTIME, ENDTIME);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\data\\fares_seats.csv' REPLACE INTO TABLE FARES_SEATS FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (SCHEDULE_ID,CLASS_ID,NUM_SEATS,NUM_FARE);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\airplanes_weekly_schedule.txt' REPLACE INTO TABLE airplanes_weekly_schedule FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID, FLIGHT_ID, WEEK_DAYS, J_TIME, S_TIME);

LOAD DATA LOCAL INFILE 'D:\\AIRLINE_RESERVATION\\newdata\\airplanes_info.txt' REPLACE INTO TABLE airplanes_info FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' (ID,PLANE_ID,CLASS_ID,NUM_SEATS,NUM_FARE);


select * from travel_class into outfile 'D:\\AIRLINE_RESERVATION\\newdata\\travel_class.txt' FIELDS  TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

select * from pass_type into outfile 'D:\\AIRLINE_RESERVATION\\newdata\\pass_type.txt' FIELDS  TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

select * from airlines into outfile 'D:\\AIRLINE_RESERVATION\\newdata\\airlines.txt' FIELDS  TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

select * from airports into outfile 'D:\\AIRLINE_RESERVATION\\newdata\\airports.txt' FIELDS  TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';

select * from route into outfile 'D:\\AIRLINE_RESERVATION\\newdata\\route.txt' FIELDS  TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n';